---
artifact: PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100
bridge: CB→QB→UE→FE→FWD→QS
canonical_hash: TBD
classification: INTERNAL–EVIDENCE-REQUIRED
ethics_guard: MAL-EEM
id: CAD-WING-BM-PARAMS-0001
llc: SYSTEMS
maintainer: GAIA Quantum Aerospace
project: PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100
release_date: 2025-09-23
utcs_mi: v5.0
version: 0.1.0
---
units:
  length: m
  angle: deg

parameters:
  span: 52.0
  reference_area: 280.0
  root_chord: 10.0
  tip_chord: 4.0
  taper_ratio: 0.4
  sweep25: 30.0
  dihedral: 5.0

  twist:
    root: 2.0
    mid: 0.0
    tip: -3.0

  airfoils:
    root: "BWBR-001 (tc=0.16, reflex)"
    mid:  "BWB-MID-001 (tc=0.14)"
    tip:  "BWBT-001 (tc=0.12)"

  thickness_to_chord:
    root: 0.16
    mid:  0.14
    tip:  0.12

  control_surfaces:
    elevons:
      deflection_limits_deg:
        min: -25
        max: 25
      segments:
        - id: EL1_L
          side: left
          span_fraction: [0.20, 0.35]
          chord_fraction: 0.25
          hinge_line_x_over_c: 0.75
        - id: EL2_L
          side: left
          span_fraction: [0.37, 0.52]
          chord_fraction: 0.25
          hinge_line_x_over_c: 0.75
        - id: EL1_R
          side: right
          span_fraction: [0.20, 0.35]
          chord_fraction: 0.25
          hinge_line_x_over_c: 0.75
        - id: EL2_R
          side: right
          span_fraction: [0.37, 0.52]
          chord_fraction: 0.25
          hinge_line_x_over_c: 0.75
    flaperons:
      deflection_limits_deg:
        min: -10
        max: 30
      segments:
        - id: FLAP_L
          side: left
          span_fraction: [0.55, 0.70]
          chord_fraction: 0.28
          hinge_line_x_over_c: 0.72
        - id: FLAP_R
          side: right
          span_fraction: [0.55, 0.70]
          chord_fraction: 0.28
          hinge_line_x_over_c: 0.72

  high_lift:
    flaps:
      type: "double-slotted"
      span_fraction: [0.20, 0.70]
      deflection_max_deg: 35.0
    slats:
      type: "Krueger"
      span_fraction: [0.15, 0.85]
      deflection_max_deg: 22.0

coordinate_systems:
  - name: AC_REF
    origin: [0.0, 0.0, 0.0]
    axes: ["+X fwd", "+Y right", "+Z up"]
  - name: WING_L
    origin: [2.5, 0.0, 0.0]
    axes: ["+x chordwise", "+y spanwise", "+z up"]