repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: structure-verify
        name: structure-verify
        entry: python3 scripts/verify_structure.py
        language: system
        types: [file]  # run on any change