repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: asi-t2-filename-policy
        name: ASI-T2 filename policy (DM + CAx)
        entry: python3 tools/lint_names.py
        language: system
        pass_filenames: true
        files: '\.(xml|step|stp|sldprt|sldasm|ipt|iam|dwg|dxf|pdf|inp|cdb|cas|dat|fem|nas|nc|eia|apt|cl|cls|qif|dmis|csv|json)$'
      - id: structure-verify
        name: structure-verify
        entry: python3 scripts/verify_structure.py
        language: system
        types: [file]  # run on any change
      - id: cad-json-validation
        name: CAD JSON Schema Validation
        entry: python3 PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/scripts/validate_json.py PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/schemas PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/geometry PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/qox_bridge
        language: system
        files: 'PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/.*\.(json)$'
      - id: cad-link-check
        name: CAD Link Validation
        entry: python3 PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/scripts/link_check.py PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD
        language: system
        files: 'PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/.*\.(json|md)$'
      - id: cad-naming-guard
        name: CAD Naming Convention Guard
        entry: python3 PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/scripts/naming_guard.py PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD
        language: system
        files: 'PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/.*'
      - id: cad-pax-validation
        name: CAD PAx Package Validation
        entry: python3 PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/pax/scripts/validate_pax.py --schema PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/pax/schemas/package.schema.json --root PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/pax
        language: system
        files: 'PRODUCTS/AMPEL360/AMPEL360_SPACE_TOURISM/PLUS/domains/AAA/cax/CAD/pax/.*\.(json|yaml|yml)$'