---
id: AAA-PAX-OB-PART-A661-0001
project: AMPEL360/BWB-Q100
artifact: PRODUCTS/AMPEL360/BWB-Q100/domains/AAA/pax/OB/manifests/partition.example.yaml
llc: SYSTEMS
classification: INTERNAL–EVIDENCE-REQUIRED
version: 0.1.0
release_date: "2025-01-23"
maintainer: "ASI-T Avionics"
bridge: "CB→QB→UE→FE→FWD→QS"
ethics_guard: MAL-EEM
utcs_mi: v5.0
canonical_hash: "sha256:abc123def456789012345678901234567890123456789012345678901234567890"
---
package_name: "A661_CDS_DisplayServer"
canonical_hash: "sha256:abc123def456789abcdef0123456789abcdef0123456789abcdef012345678ab"
sbom_hash: "sha256:def456abc789012bcdef123456789abcdef0123456789abcdef012345678abcd"
utcs_signature: "signature-value-placeholder"
security_policy_id: "policy-001"
package:
  name: "A661_CDS_DisplayServer"
  kind: "OB-PARTITION"
  target:
    platform: "IMA"
    rtos: "INTEGRITY-178B"   # o VxWorks653/Deos (ejemplo)
  resources:
    cpu: 0.5
    memory_mb: 128
    storage_mb: 64
  interfaces:
    arinc653_ports:
      - name: "CDS_CMD_IN"   # sampling
        direction: "IN"
        period_ms: 20
      - name: "CDS_STAT_OUT" # queuing
        direction: "OUT"
        depth: 8
    a664_vlinks:
      - name: "VL-CDS-01"
        bw_mbps: 4
        bag_us: 8000
  sbom: "../../OB/sbom/A661_CDS_DisplayServer.spdx.json"
  dependencies: []
security:
  signing:
    method: "sigstore-cosign"
    signature_path: "../../OB/certificates/A661_CDS_DisplayServer.sig"
  constraints:
    hm_policy: "partition_hm_policy_v1"
evidence:
  canonical_hash: "sha256:abc123def456789abcdef0123456789abcdef0123456789abcdef012345678ab"
  sbom:
    path: "../../OB/sbom/A661_CDS_DisplayServer.spdx.json"
    hash: "sha256:def456abc789012bcdef123456789abcdef0123456789abcdef012345678abcd"
  signatures:
    - path: "../../OB/certificates/A661_CDS_DisplayServer.sig"
      type: "cosign"
      keyid: "key-123"
  security_policy_id: "policy-001"
  qs_path: "PRODUCTS/AMPEL360/BWB-Q100/QS/OB/A661_CDS_DisplayServer/"
  attestations:
    - "in-toto/attest-build.jsonl"