# UTCS-MI v5.0 Compliant Partition Manifest Example
# 
# CANONICAL HASH MAINTENANCE:
# The 'canonical_hash' field appears in three locations and must be kept synchronized:
# 1. utcs_header.canonical_hash - Hash of the entire UTCS header section
# 2. Root-level canonical_hash - Hash of the complete manifest (excluding UTCS header)
# 3. evidence.canonical_hash - Copy of root-level canonical_hash for evidence tracking
#
# To update canonical_hash values after making changes:
# 1. Temporarily set all canonical_hash fields to "TBD" or a placeholder
# 2. Compute SHA256 hash of the normalized manifest content:
#    - For utcs_header.canonical_hash: hash the UTCS header YAML section only
#    - For root canonical_hash: hash the entire manifest excluding the UTCS header
#    - For evidence.canonical_hash: use the same value as root canonical_hash
# 3. Use: cat manifest.yaml | yq eval 'del(.utcs_header)' | sha256sum
#    or similar tools to compute the hash of the canonical form
# 4. Update all three canonical_hash fields with the computed SHA256 values
#    Format: "sha256:<64 lowercase hex characters>"
#
# Note: The sbom_hash field should contain the actual SHA256 hash of the SBOM file
# referenced in evidence.sbom.path. Compute it with: sha256sum <sbom-file>
#
---
utcs_header:
  id: AAA-PAX-OB-PART-A661-0001
  project: AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100
  artifact: PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100/domains/AAA/pax/OB/manifests/partition.example.yaml
  llc: SYSTEMS
  classification: INTERNAL–EVIDENCE-REQUIRED
  version: 0.1.0
  release_date: "2025-01-23"
  maintainer: "ASI-T Avionics"
  bridge: "CB→QB→UE→FE→FWD→QS"
  ethics_guard: MAL-EEM
  utcs_mi: v5.0
  canonical_hash: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

package_name: "A661_CDS_DisplayServer"
canonical_hash: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
sbom_hash: "sha256:fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321"
utcs_signature: "signature-A661-CDS-DisplayServer-v0.1.0"
security_policy_id: "policy-001"

package:
  name: "A661_CDS_DisplayServer"
  kind: "OB-PARTITION"
  target:
    platform: "IMA"
    rtos: "INTEGRITY-178B"   # o VxWorks653/Deos (ejemplo)
  resources:
    cpu: 0.5
    memory_mb: 128
    storage_mb: 64
  interfaces:
    arinc653_ports:
      - name: "CDS_CMD_IN"   # sampling
        direction: "IN"
        period_ms: 20
      - name: "CDS_STAT_OUT" # queuing
        direction: "OUT"
        depth: 8
    a664_vlinks:
      - name: "VL-CDS-01"
        bw_mbps: 4
        bag_us: 8000
  sbom: "../../OB/sbom/A661_CDS_DisplayServer.spdx.json"
  dependencies: []

security:
  signing:
    method: "sigstore-cosign"
    signature_path: "../../OB/certificates/A661_CDS_DisplayServer.sig"
  constraints:
    hm_policy: "partition_hm_policy_v1"

evidence:
  canonical_hash: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  sbom:
    path: "../../OB/sbom/A661_CDS_DisplayServer.spdx.json"
    hash: "sha256:fedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321"
  signatures:
    - path: "../../OB/certificates/A661_CDS_DisplayServer.sig"
      type: "cosign"
      keyid: "key-123"
  security_policy_id: "policy-001"
  qs_path: "PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100/QS/OB/A661_CDS_DisplayServer/"
  attestations:
    - "in-toto/attest-build.jsonl"