---
id: CAD-WING-BM-PARAMS-0001
project: AMPEL360/BWB-Q100
artifact: domains/AAA/cax/CAD/wing_baseline_model/master_model/params.yaml
llc: SYSTEMS
classification: INTERNAL–EVIDENCE-REQUIRED
version: 0.1.0
release_date: 2025-09-23
maintainer: "GAIA Quantum Aerospace"
bridge: "CB→QB→UE→FE→FWD→QS"
ethics_guard: MAL-EEM
utcs_mi: v5.0
canonical_hash: "TBD"
---
units:
  length: m
  angle: deg

parameters:
  span: 52.0
  reference_area: 280.0
  root_chord: 10.0
  tip_chord: 4.0
  taper_ratio: 0.4
  sweep25: 30.0
  dihedral: 5.0

  twist:
    root: 2.0
    mid: 0.0
    tip: -3.0

  airfoils:
    root: "BWBR-001 (tc=0.16, reflex)"
    mid:  "BWB-MID-001 (tc=0.14)"
    tip:  "BWBT-001 (tc=0.12)"

  thickness_to_chord:
    root: 0.16
    mid:  0.14
    tip:  0.12

  control_surfaces:
    elevons:
      count_per_side: 2
      span_fractions: [[0.20, 0.35], [0.37, 0.52]]
      chord_fraction: 0.25
    flaperons:
      count_per_side: 1
      span_fraction: [0.55, 0.70]
      chord_fraction: 0.28

  high_lift:
    flaps:
      type: "double-slotted"
      span_fraction: [0.20, 0.70]
      deflection_max: 35.0
    slats:
      type: "Krueger"
      span_fraction: [0.15, 0.85]
      deflection_max: 22.0

coordinate_systems:
  - name: AC_REF
    origin: [0.0, 0.0, 0.0]
    axes: ["+X fwd", "+Y right", "+Z up"]
  - name: WING_L
    origin: [2.5, 0.0, 0.0]
    axes: ["+x chordwise", "+y spanwise", "+z up"]