name: CXP Publish
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: cxp-publish-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 1
      
      - name: Set up Python
        uses: actions/setup-python@e797f83eb5946cedff3ea72a57c0b9d286b6cdce  # v6.0.0
        with:
          python-version: '3.x'
      
      - name: Generate SBOM (SPDX)
        uses: anchore/sbom-action@f8bdd1d8ac5e901a77a92f111440fdb1b593736b  # v0.20.6
        with:
          output-file: sbom/spdx.sbom.json
          format: spdx-json
      
      - name: Stamp manifest
        run: |
          set -euo pipefail
          dt=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq \
            --arg sha "${GITHUB_SHA}" \
            --arg dt "$dt" \
            '.provenance.hash=$sha | .provenance.generated_at=$dt' \
            UTCS/context.manifest.json > UTCS/context.manifest.stamped.json
          mv UTCS/context.manifest.stamped.json UTCS/context.manifest.json
      
      - name: Validate manifest (JSON Schema)
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7  # v3.1.1
        with:
          schema: UTCS/context.schema.json
          file: UTCS/context.manifest.json
      
      - name: TT reward (CXP publish)
        run: |
          python tools/tek_tokens.py auto --event cxp-publish \
            --actor "${{ github.actor }}" --run-id "${{ github.run_id }}"
      
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: utcs-cxp
          path: |
            UTCS/context.manifest.json
            UTCS/links.map.json
            sbom/spdx.sbom.json
