name: struct-and-brex
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  derive-struct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python scripts/derive_struct_from_readmes.py --check --brex-strict --emit-index QS/extract/global_index.yaml