name: TT Token Verification

on:
  push:
    paths:
      - 'finance/**'
      - 'tools/tek_tokens.py'
      - '.github/workflows/tek-tokens-verify.yml'
  pull_request:
    paths:
      - 'finance/**'
      - 'tools/tek_tokens.py'
  workflow_dispatch:

jobs:
  verify-tokens:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Verify tokenomics configuration
        run: |
          echo "=== Validating tokenomics configuration ==="
          if [ -f finance/teknia.tokenomics.json ]; then
            echo "✓ Tokenomics file exists"
            python3 -m json.tool finance/teknia.tokenomics.json > /dev/null
            echo "✓ Tokenomics JSON is valid"
          else
            echo "✗ Tokenomics file not found"
            exit 1
          fi
      
      - name: Check CLI tool
        run: |
          echo "=== Checking CLI tool ==="
          if [ -f tools/tek_tokens.py ]; then
            echo "✓ CLI tool exists"
            python3 tools/tek_tokens.py --help > /dev/null
            echo "✓ CLI tool is executable"
          else
            echo "✗ CLI tool not found"
            exit 1
          fi
      
      - name: Display balances (if ledger exists)
        run: |
          echo "=== Current Token Balances ==="
          if [ -f finance/ledger.json ]; then
            python3 tools/tek_tokens.py balance
          else
            echo "Ledger not initialized yet. Run 'python tools/tek_tokens.py init' to initialize."
          fi
      
      - name: Verify badge generation
        run: |
          echo "=== Testing Badge Generation ==="
          if [ -f finance/ledger.json ]; then
            python3 tools/tek_tokens.py verify
            if [ -f finance/token_badge.json ]; then
              echo "✓ Badge generated successfully"
              cat finance/token_badge.json
            else
              echo "✗ Badge generation failed"
              exit 1
            fi
          else
            echo "Skipping badge generation (ledger not initialized)"
          fi
      
      - name: Validate ledger integrity (if exists)
        run: |
          echo "=== Validating Ledger Integrity ==="
          if [ -f finance/ledger.json ]; then
            python3 -m json.tool finance/ledger.json > /dev/null
            echo "✓ Ledger JSON is valid"
            
            # Check total supply matches genesis
            python3 << 'EOF'
          import json
          
          with open('finance/ledger.json', 'r') as f:
              ledger = json.load(f)
          
          with open('finance/teknia.tokenomics.json', 'r') as f:
              tokenomics = json.load(f)
          
          total_distributed = sum(ledger['accounts'].values())
          expected_supply = tokenomics['conversion']['total_genesis_supply_deg']
          
          print(f"Total distributed: {total_distributed:,} deg")
          print(f"Genesis supply: {expected_supply:,} deg")
          
          if total_distributed == expected_supply:
              print("✓ Total distributed matches genesis supply")
          else:
              print(f"✗ Supply mismatch! Difference: {expected_supply - total_distributed:,} deg")
              exit(1)
          EOF
          else
            echo "Ledger not initialized yet."
          fi
      
      - name: Summary
        run: |
          echo ""
          echo "=== TT Token System Verification Complete ==="
          echo "Genesis Supply: 2,000,000,000 TT (720,000,000,000 deg)"
          echo "Divisibility: 360 deg per TT"
          echo "Ledger: Integer deg units"
          echo ""
          echo "All checks passed! ✓"
