name: TT Token Verification

on:
  push:
    paths:
      - 'finance/**'
      - 'tools/tek_tokens.py'
      - '.github/workflows/tek-tokens-verify.yml'
  pull_request:
    paths:
      - 'finance/**'
      - 'tools/tek_tokens.py'
  workflow_dispatch:

jobs:
  verify-tokens:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verify tokenomics configuration
        run: |
          # ...same as main branch logic...

      - name: Check CLI tool
        run: |
          # ...same as main branch logic...

      - name: Display balances (if ledger exists)
        run: |
          # ...same as main branch logic...

      - name: Verify badge generation
        run: |
          # ...same as main branch logic...

      - name: Validate ledger integrity (if exists)
        run: |
          # ...same as main branch logic...

      - name: Upload badge
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tt-badge
          path: finance/token_badge.json

      - name: Summary
        run: |
          # ...same as main branch logic...
